hydroserver2/hydroserver-data-management-app

src/App.vue
src/components/account/AccountForm.vue
src/store/authentication.ts
src/utils/api/apiMethods.ts
src/utils/rules.ts

Adjusts field binding to prevent an issue where fields would appear permanently invalid.

[#13] Account form invalid fields

---

src/store/authentication.ts
src/utils/api/responseInterceptor.ts
src/utils/api/toastHandler.ts

Fixes for the issues linked in each commit

59 account

---

src/components/DataSource/DataSourceSchedule.vue

add * to data source interval

---

src/components/Datastream/DatastreamTable.vue
src/components/Datastream/DatastreamTableActions.vue
src/types.ts

80 private observations

---

src/components/base/Footer.vue
src/config/policyConfig.ts

Add config directory; add terms of use config

---

package-lock.json
package.json
src/components/GoogleMap.vue
src/pages/Browse.vue
src/utils/googleMaps/markers.ts

hydroserver2/hydroserver#65
Added a useMarkerClusterer prop on the GoogleMap component. I added it to just the browse page for now, but may add it to the My Sites page later

Add marker clustering GoogleMaps

---

cypress/e2e/account/login.cy.ts
src/components/Metadata/DeleteMetadataCard.vue
src/components/Metadata/ObservedPropertyFormCard.vue
src/components/Metadata/ObservedPropertyTable.vue
src/components/Metadata/ProcessingLevelFormCard.vue
src/components/Metadata/ProcessingLevelTable.vue
src/components/Metadata/ResultQualifierTable.vue
src/components/Metadata/SensorTable.vue
src/components/Metadata/UnitFormCard.vue
src/components/Metadata/UnitTable.vue
src/composables/useTableLogic.ts
src/pages/Sites.vue
src/services/api.ts

hydroserver2/hydroserver#86
Updated frontend to use backend's new query params for returning only owned/unowned data

Query only the data we need from backend

---

src/pages/account/Profile.vue
vite.config.ts

Exclude Vuetify optimization in development

---

src/utils/googleMaps/markers.ts

Fix map marker selection

---

package-lock.json
package.json
src/components/Site/SiteDetailsTable.vue
src/components/Site/SiteForm.vue
src/types/index.ts
src/utils/googleMaps/mapUtils.ts

hydroserver2/hydroserver#111
Have user select 2-digit country code and country name from ISO 3166-1-alpha-2. Also populate the correct selection from list (or nothing if not found) when user clicks on map on the SiteForm.

Add Country to Sites Location

---

src/components/GoogleMap.vue
src/components/Site/SiteForm.vue
src/config/googleMapsConfig.ts
src/pages/Browse.vue
src/pages/Sites.vue
src/utils/googleMaps/loadMap.ts

hydroserver2/hydroserver#101
If there's only on marker, sites page looks like this: 
Multiple markers will zoom to the LatLngBounds like so:

101 map config

---

src/components/Browse/BrowseFilterTool.vue
src/pages/Browse.vue

hydroserver2/hydroserver#118
Before and after

118 browse filter

---

src/pages/Contact.vue

Make GitHub Link open new tab

---

src/components/Site/SiteForm.vue

Update SiteForm country to v-autoselect for searching

---

src/pages/Sites.vue

Increase Sites map height from 25rem to 33rem

---

src/components/Browse/BrowseFilterTool.vue
src/pages/Browse.vue

129 browse navigation drawer

---

src/components/GoogleMap.vue
src/components/Site/SiteFilterTool.vue
src/pages/Sites.vue
src/utils/googleMaps/markers.ts

130 sites filter tool

---

src/components/Sparkline.vue
src/utils/FocusContextPlot.ts

Plot - Remove line at 0; Fill from minY to Value

---

src/components/account/AccountForm.vue

131 org delete dialog

---

src/pages/Sites.vue

126 loading pages

---

src/components/Site/SiteTagManager.vue

Make keys unique for site tags

---

src/components/account/AccountForm.vue
src/pages/account/CompleteProfile.vue
src/pages/account/Profile.vue
src/pages/account/Signup.vue

134 account form

---

src/pages/SiteDetails.vue

Move data disclaimer above datastream table

---

package-lock.json
package.json

hydroserver2/hydroserver#153
Fixed the problem by updating GoogleMaps.

Update GoogleMaps dependencies

---

src/components/Site/SiteDetailsTable.vue
src/components/Site/SiteTagManager.vue

Add URL detection to SiteDetails page metadata tags

---

src/components/TimeSeriesAnalyst/DatastreamInformationCard.vue
src/components/TimeSeriesAnalyst/DatePickerField.vue
src/components/TimeSeriesAnalyst/TSADatasetsTable.vue
src/components/TimeSeriesAnalyst/TSAFiltersDrawer.vue
src/components/TimeSeriesAnalyst/TSATimeFilters.vue
src/components/TimeSeriesAnalyst/TSAVisualizationCard.vue
src/pages/SiteDetails.vue
src/pages/TimeSeriesAnalyst.vue
src/store/timeSeriesAnalyst.ts

hydroserver2/hydroserver#159
Updated the TSA filtering including time filters and adding search fields for each filter

159 mutual filtering

---

src/composables/__tests__/useMetadata.spec.ts
src/composables/useMetadata.ts
src/pages/DatastreamForm.vue

178 fix fetch metadata

---

src/pages/DatastreamForm.vue
src/types/index.ts

hydroserver2/hydroserver#182
Updated the frontend to use a string for time agg. While I was working with the component, I also updated the UI to conform to material design 3:

182 time agg

---

src/pages/SiteDetails.vue

Resolves hydroserver2/hydroserver#183

Restrict site deletion to primary owner

---

src/components/VisualizeData/DataVisDatasetsTable.vue
src/components/VisualizeData/DataVisTimeFilters.vue
src/components/VisualizeData/DataVisualizationCard.vue
src/components/VisualizeData/DatastreamInformationCard.vue
src/components/VisualizeData/DatePickerField.vue
src/pages/VisualizeData.vue
src/store/dataVisualization.ts
src/store/observations.ts
src/utils/CSVDownloadUtils.ts

Resolves hydroserver2/hydroserver#190

190 qc updates

---

src/components/Datastream/DatastreamTableActions.vue
src/components/Site/SiteAccessControl.vue
src/components/Site/SiteDeleteModal.vue
src/components/account/DeleteAccountCard.vue

Resolves hydroserver2/hydroserver#191

191 single site

---

index.html
package-lock.json
package.json
src/components/Browse/BrowseFilterTool.vue
src/components/Datastream/DatastreamTemplateModal.vue
src/components/Site/SiteDetailsTable.vue
src/components/Site/SiteForm.vue
src/components/account/OrganizationTable.vue
src/components/account/UserInfoTable.vue
src/composables/useMetadata.ts
src/pages/DatastreamForm.vue
src/pages/SiteDetails.vue
src/pages/Sites.vue
src/pages/account/CompleteProfile.vue
src/plugins/vuetify.ts
src/store/authentication.ts
src/store/index.ts
src/store/user.ts
src/utils/__tests__/storage.spec.ts
src/utils/storage.ts

Resolves hydroserver2/hydroserver#200
Sorted datastream lists. and made newly created linked metadata get populated in field after getting created ds form.
Triggering a validate on just the intended time spacing field when updating the unit couldn't be done with Vuetify's rules system.

Sort DatastreamForm's 'load template' list

---

index.html
package-lock.json
package.json
src/components/Browse/BrowseFilterTool.vue
src/components/Datastream/DatastreamTemplateModal.vue
src/components/Site/SiteDetailsTable.vue
src/components/Site/SiteForm.vue
src/components/account/OrganizationTable.vue
src/components/account/UserInfoTable.vue
src/composables/__tests__/useMetadata.spec.ts
src/composables/useMetadata.ts
src/pages/DatastreamForm.vue
src/pages/SiteDetails.vue
src/pages/Sites.vue
src/pages/account/CompleteProfile.vue
src/plugins/vuetify.ts
src/store/authentication.ts
src/store/index.ts
src/store/user.ts
src/utils/__tests__/storage.spec.ts
src/utils/storage.ts

Resolves hydroserver2/hydroserver#202
I created this branch from the @200-test branch because I added sorting for the datastream form selection boxes in 200 that I wanted to use for this issue. 
Checked that the formatted names can be as long as the enforced 200 maximum characters. If all three parts of the combined title are long, then the selection box will ... when it hits the full width of the page.
An image of normal use, sorted by the formatted title:

202 op title

---

src/components/Site/SiteFilterToolbar.vue
src/components/Site/SiteTagManager.vue
src/components/base/Navbar.vue
src/pages/Sites.vue
src/router/routes.ts

Resolves hydroserver2/hydroserver#211

211 site filters

---

src/pages/Browse.vue
src/pages/DataSourceDetail.vue
src/pages/DatastreamForm.vue
src/pages/Sites.vue
src/pages/VisualizeData.vue

Resolves hydroserver2/hydroserver#215

Added notifications to tell the user about API failures

---

src/components/DataLoader/DataLoaderTable.vue
src/components/DataSource/DataSourceTable.vue
src/components/Metadata/ObservedPropertyTable.vue
src/components/Metadata/ProcessingLevelTable.vue
src/components/Metadata/ResultQualifierTable.vue
src/components/Metadata/SensorTable.vue
src/components/Metadata/UnitTable.vue
src/pages/DataLoaderDashboard.vue
src/pages/DataSourceDashboard.vue
src/pages/Metadata.vue

Resolves hydroserver2/hydroserver#214
Updated the styling of the three data management tables to be consistent with the rest of the webapp. Updated the tabs on the manage metadata table to stand out more & added a search bar on that table.

214 tab styling

---

src/components/base/Navbar.vue
src/config/Home.vue
src/config/googleMapsConfig.ts
src/config/homeConfig.ts
src/config/navbarConfig.ts
src/router/routes.ts

Resolves hydroserver2/hydroserver#217

217 landing page

---

src/components/Browse/BrowseFilterTool.vue

Resolves hydroserver2/hydroserver#218

Fix browse page title styling not loading

---

src/services/api.ts

Fix visualizeData page not fetching last observation

---

src/pages/VisualizeData.vue

Resolves hydroserver2/hydroserver#235
Updated url handling to allow names to have special characters like commas and spaces. Added type safety so the query parameters are always arrays of strings.

Fix special characters not working in copied state url

---

src/config/microsoftClarityConfig.ts
src/main.ts
src/plugins/clarity.ts

Resolves hydroserver2/hydroserver#306
Added a config file for the user to turn on Clarity and provide their project ID.

Add option to use Microsoft Clarity

---

src/components/Datastream/DatastreamTable.vue
src/components/Observation/ObservationsDeleteCard.vue
src/composables/useWorkspacePermissions.ts
src/services/api.ts

Resolves hydroserver2/hydroserver#243

Add datastream data delete functionality
